version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: go-db
    restart: unless-stopped
    ports:
      - "2345:5432"
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - go_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_admin -d tododb"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: go-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - go_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local

networks:
  go_network:
    driver: bridge
